name = "SystemBenchmark"
uuid = "30cdaa97-48ad-4abc-9688-3a7175b8083d"
version = "0.4.1"

[deps]
BenchmarkTools = "6e4b80f9-dd63-53aa-95a3-0cdb28fa8baf"
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
CUDA = "052768ef-5323-5732-b1bb-66c8b64840ba"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
Downloads = "f43a241f-c20a-4ad4-852c-f6b1247861c6"
GitHub = "bc5e4493-9b4d-5f90-b8aa-2b2bcaad7a26"
InteractiveUtils = "b77e0a4c-d291-57a0-90e8-8db25a27a240"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Logging = "56ddb016-857b-54e1-b83d-db4d58db5568"
Pkg = "44cfe95a-1eb2-52ea-b672-e2afdf69b78f"
ProgressMeter = "92933f4c-e287-5a05-a399-4b506db050ca"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
VideoIO = "d6d074c3-1acf-5d4c-9a43-ef38773959a2"

[compat]
BenchmarkTools = "0.5, 0.6, 0.7, 1"
CSV = "0.6, 0.7, 0.8, 0.9"
CUDA = "1.1, 2.0, 2.1, 2.2, 2.3, 3.0"
DataFrames = "0.21, 0.22, 1"
GitHub = "5.1"
ProgressMeter = "1.3"
VideoIO = "0.9"
julia = "1.6"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
